### ISSUE TITLE
Allow for config key override

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/mailsystem#23]
Further to https://github.com/backdrop/backdrop-issues/issues/5537 where core's mail needs to change to allow overriding in the settings.php file, this module should also be updated.

**Comment by herbdool** [comment]
@eric2pin please test this if you've got a moment.

**Comment by eric2pin** [comment]
@herbdool This works great! Config overrides now appear in the Mail System module config screen at admin/config/system/mailsystem
