### ISSUE TITLE
Drupal 7 Migration is Broken Due to Incorrect Logic

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/mailsystem#26]
Incorrect logic/syntax is being used on line 58 and 59 of `mailsystem.install`

Here is the issue:

```
config_set('system.mail', 'default-system', update_variable_get('mail_system'), 'DefaultMailSystem');
config_set('mailsystem.settings', 'mailsystem_theme', update_variable_get('mailsystem_theme'), 'current');
  ```

Since a value for  `mail_system` may not exist in Drupal 7, instead of using the value of `DefaultMailSystem` it will use NULL since the second argument to `update_variable_get` in the event a NULL value is returned is not being specified correctly.

This is the same for `mailsystem_theme`

Here is the updated code:

```
/**
 * Migrate variables from Drupal 7 to Backdrop.
 */
function mailsystem_update_1000() {
  // migrate variables
  config_set('system.mail', 'default-system', update_variable_get('mail_system', 'DefaultMailSystem'));
  config_set('mailsystem.settings', 'mailsystem_theme', update_variable_get('mailsystem_theme', 'current'));

  // Delete variables.
  update_variable_del('mail_system');
  update_variable_del('mailsystem_theme');
}
```

Cheers!

**Comment by rbargerhuff** [comment]
Hi, just wondering why the PR for the issue has not been accepted yet? Thank you.

**Comment by herbdool** [comment]
Merged. Thanks @rbargerhuff! I had just noticed.
