### ISSUE TITLE
Mailsystem config data settings.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/mailsystem#7]
There seems to be a bit of a problem regarding the data held by this module and it needs a rethink.

It should surely hold two types of list: one being a record of modules providing some form of mail system for handling the sending of mail e.g. mimemail; the other being a record of modules wishing to be able to send mail and offering a template to be used by, for example, mimemail. 

This latter information requires the user modules to provide a function mailsystem_set() provided in mailsystem.module. I am proposing to add a config setting mailsystem_user_modules for these.

The information about modules that provide a mail service (i.e. which implement MailSystemInterface) is collected by function &mailsystem_get_classes() also in mailsystem.module.

**Comment by Graham-72** [comment]
After a long interval I have been looking again at this module and I realise that it is not completely fulfilling its purpose which, surely, is to manage all the settings in the core config file system.mail which contains the key-value pairs linking functions that use Backdrops mail system with the mail system class that they should use.

I propose to modify mailsystem.admin.inc so that all entries in system.mail are displayed and can be reassigned to any of the mail system classes available in the system e.g. MimeMailSystem instead of DefaultMailSystem.

**Comment by herbdool** [comment]
This is now out of date.
